### PR TITLE
Add brightness toggle and readme typo

### PR DESCRIPTION
**Pull request by mxygem**
Heya! Taking a crack at adding a dark mode and having it as a toggle. Let me know what you think?

toggle

### CODE REVIEW

**Comment by mxygem** [comment]
Quick note: I did this on a Win 7 machine and things like cp don't work, so I copied the CSS into the build folder manually.  Everything still works and looks like normal, so I think it's GTG!

**Comment by callum-oakley** [comment]
Thanks a lot for this! By and large I like it, with one irk:

How do you feel about making the typed text brighter than the "to be typed" text? In the light version the to be typed text is low contrast (almost just like a guide), and the text you've typed is higher contrast. The dark mode at the moment reverses this convention. The lower contrast text is also a litte *too* low contrast for my eyes, it's quite hard to read!

The colours I'm using for the light theme are: https://github.com/NLKNguyen/papercolor-theme

It might be nice to source the dark colours from the same theme (there's a dark theme in there too).

**Comment by mxygem** [comment]
You're very welcome and thanks! Ah yeah, that makes sense in regard to the text color. 

When I was working on things I did try just swapping the background color with the text color but it wasn't dark enough for me. (something, something my soul is black?) 

Anyway! I've just looked at the theme's dark version and it looks good to me! Guessing you pulled the colors from their [color file](https://github.com/NLKNguyen/papercolor-theme/blob/master/colors/PaperColor.vim), yeah?

I'll get it taken care of tonight, my time (Arizona, USA) if I can, otherwise it'll be "soon"!

Any other changes you'd like while I'm in there?

**Comment by callum-oakley** [comment]
Yeah, or with slightly less noise to sift through: https://github.com/NLKNguyen/papercolor-16/tree/master/base16-builder-schemes

Other than that I can't think of anything else I'd want to change. :)

**Comment by mxygem** [comment]
I think I've got everything set now? I did a bit of work to get the behavior of dark/light handled correctly. Individual items have their class set appropriately upon toggling including cases for errors, backspace, and the cursor. Aka, there were a number of cases where class behavior would be a bit funky across toggles. For instance: when deleting, all classes would be removed, so if you toggled immediately after, without typing those characters again, they'd end up dark.

Have a look and enjoy! If I missed something, let me know. Happy to fix.

**Comment by mxygem** [comment]
Just uncovered another case to solve for!  (Done)

**Comment by mxygem** [comment]
Side question: What're your thoughts on adding buttons for increasing/decreasing font size? For me it's pretty small off the bat.

**Comment by callum-oakley** [comment]
Great! Happy to merge this now, thanks for the contribution :)

I think zooming in your browser _should_ be enough? Although I wouldn't be completely opposed to including font size change buttons if they were tastefully done.

**Comment by mxygem** [comment]
You're very welcome! 

Yeah, browser zoom is how I've handled it in the past. It's definitely be something I'd do while keeping in the current minimalist style if I did it. 

Thanks for being open to my code and merging it!

**Pull request merged**
